config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  resources :flights
  resources :bookings

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/airport.rb
class Airport < ActiveRecord::Base
	has_many :flights, foreign_key: :departure_id
	has_many :departing_flights, through: :flights, source: :departure_airport 
	
	has_many :reverse_flights, foreign_key: :arrival_id, class_name: "Flight"
	has_many :arriving_flights, through: :reverse_flights, source: :arrival_airport
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :flight
	has_many :groups
	has_many :passengers, through: :groups
	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
	belongs_to :departure_airport, foreign_key: :departure_id, class_name: "Airport"
	belongs_to :arrival_airport, foreign_key: :arrival_id, class_name: "Airport"
	has_many :bookings
	has_many :passengers, through: :bookings
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :booking
	belongs_to :passenger
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
	has_many :groups
	has_many :bookings, through: :groups
	has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	
	def new
		@booking = Booking.new(flight_id: params[:flight_id])
		params[:passengers].to_i.times { @booking.passengers.build }
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save
			redirect_to @booking
		else
			render 'new'
		end
	end

	def show
		@booking = Booking.find(params[:id])
		@passengers = @booking.passengers
		@flight = @booking.flight
		@from = @flight.departure_airport
		@to = @flight.arrival_airport
	end

	private

		def booking_params
			params.require(:booking).permit(:flight_id,
										 									passengers_attributes: [:name, :email])
		end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

	def index
		@departure_options = Flight.all.map{ |f| [f.departure_airport.code, f.departure_id ] }
		@arrival_options = Flight.all.map{ |f| [f.arrival_airport.code, f.arrival_id] }
		if params.has_key?(:departure_id)
			@found_flights = Flight.all.where(departure_id: params[:departure_id], arrival_id: params[:flight][:arrival_id], date: params[:flights][:date])
		end
		@booking = Booking.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class="row">
	<div class="col-sm-offset-3 col-sm-6">
		<%= form_for(@booking) do |f| %>
			<%= f.hidden_field :flight_id, value: params[:flight_id] %>
			<h2>Passengers:</h2>
			<%= f.fields_for :passengers do |user| %>
				<%= user.label :name %>
				<%= user.text_field :name %>

				<%= user.label :email %>
				<%= user.text_field :email %>
			<% end %>
			<%= f.submit class:"btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/bookings/show.html.erb
<h1>Booking Info</h1>

<div class="row">
	<div class="col-sm-offset-2 col-sm-8 booking-info">
		<ul>
			<li><strong>From:</strong> <%= @from.name %> (<%= @from.code %>)</li>
			<li><strong>To:</strong> <%= @to.name %> (<%= @to.code %>)</li>
			<li><strong>Departs:</strong> <%= @flight.date %> <strong>at:</strong> <%= @flight.departure_time %></li>
			<li><strong>Arrives:</strong> <%= @flight.date %> at: <%= @flight.arrival_time %></li>
			<li><strong>Passengers:</strong></li>
			<ol>
				<% @passengers.each do |passenger| %>
					<li><%= passenger.name  %> :: <%= passenger.email %></li>
				<% end %>
			</ol>
		</ul>
	</div>
</div>

app/views/flights/_found_flights.html.erb
<% if @found_flights.size > 0 %>	
	<table class="flights_avail">
		<thead>
			<th>From</th>
			<th>To</th>
			<th>Departs</th>
			<th>Arrives</th>
			<th>Select</th>
		</thead>
		<tbody>
		<%= form_tag new_booking_path, method: :get do %>	
			<% @found_flights.each do |flight| %>
				<tr>
					<td><%= flight.departure_airport.name %></td>
					<td><%= flight.arrival_airport.name %></td>
					<td><%= flight.departure_time.strftime "%m-%d %H:%M:%S" %></td>
					<td><%= flight.arrival_time.strftime "%m-%d %H:%M:%S" %></td>
					<td><%= radio_button_tag(:flight_id, flight.id) %></td>
				</tr>
			<% end %>
	</table>
			<%= hidden_field_tag :passengers, params[:passengers] %>
			<%= submit_tag "Book Flight", class: "btn btn-large btn-primary" %>
		<% end %>
<% else %>
	<h2>Sorry, No Flights Were Found</h2>
<% end %>

app/views/flights/index.html.erb
<div class="row">
	<div class="col-sm-3 sidebar">
		<h1>Search Flights</h1>
		<%= form_for("flights", url: "#index", html: { method: "GET" }) do |f| %>
			<%= f.label :departure_id, "From:" %>
			<%= select_tag(:departure_id, options_for_select(@departure_options)) %>

			<%= f.label :arrival_id, "To:" %>
			<%= select(:flight, :arrival_id, @arrival_options) %>
			
			<%= f.label :date, "Departure Date" %>
			<%= f.text_field :date, value: Date.today %>

			<%= label_tag :passengers %>
			<%= number_field_tag :passengers, in: (1..4) %>

			<%= f.submit "Search", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
	<div class="col-sm-9 found_flights">
		<h1>Flights Available</h1><hr />
		<% if @found_flights %>
			<%= render 'found_flights' %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>